### ISSUE TITLE
Bug: $ token balances calculated incorrectly

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/safe-config-service#67]
_Copying bug reported by @douglasqian on Telegram_

> Congrats on launching the new Celo Safe! Looks a lot nicer than the old one 🙂
> Noticed a small issue here with value of tokens? Seems like it’s off for both Celo & cUSD

Previously: 

![Image](https://user-images.githubusercontent.com/46296830/203140169-85062c28-52f4-459a-9ceb-953311c67868.jpg)

Now:

![Image](https://user-images.githubusercontent.com/46296830/203140151-2b49c777-5537-4a56-a04d-842b3b4652c5.jpg)

**Comment by martinvol** [comment]
This was actually an issue in the tx services, fixed in the PRs listed in history
